---
title: "Diamond sizes"
author: Rajas Purohit
date: 05-22-2023
output: word_document
---

``` {r, echo = FALSE}
#Note, Each gray box below is a code chunk. You need to insert a code chunk and put your R code in it. By setting echo = FALSE. this comment and any code will not show in my output document. If it were TRUE, the comment and code would appear. 
```

``` {R my first R chunk}
print("Hello in Markdown!")
head(Titanic)
```

```{r setup, include = FALSE}
#The include = FALSE function hides both the code and output in my output document

#You need to install these packages first to be able to use the functions within them. You can install them from the Tools tab or write a new code chunk: install.packages("package_name"). 
library(ggplot2)
library(dplyr)
```

```{r, include = FALSE}
#this next line is creating a subset called 'smaller' of the diamonds data
smaller <- diamonds %>% 
  filter(carat <= 1)
```

```{r, echo = FALSE}
#This next chunk is inline code. Inline code puts the text with the output of the function in my document.
```

We have data about `r nrow(diamonds)` diamonds. Only 
`r nrow(diamonds) - nrow(smaller)` are larger than
1 carat. The distribution of the remainder is shown
below:

``` {r, echo = FALSE}
#This next code chunk will make a plot in our output doc
```

```{r, echo = FALSE}
smaller %>% 
  ggplot(aes(carat)) + 
  geom_freqpoly(binwidth = 0.01)
```

```{r, echo = FALSE}
#Once all of my code has been written, I click on the Knit button in the tool bar above to produce my document.
```

```{r, embedding code from ANA 505 week 4 activity}
# Week 4: dplyr package
```

```{r, create dataframe from the Titanic dataset and check top rows}
#Task: Write the function to get a dataset from Base R: Titanic
#and give the dataframe a new name of your choice
#(hint: you will want your data to be a dataframe. Use the function: as.data.frame(Titanic))
titanic <- as.data.frame(Titanic)

#See the top rows of the data
#TASK: Write the function to see the top rows of the data
head(titanic)
```

```{r, installing dplyr}
#Install and call the package dplyr
#TASK: Write the functions to install and call dplyr
#install.packages("dplyr")
library(dplyr)
```

```{r, using select}
#Let's just see the Survived and Sex columns
#Task: Write the function to 'select' the Survived and Sex columns 
#(hint: use the 'select' function)
#titanic_select <- as_tibble(titanic)
#titanic_select %>% select(Survived, Sex)
select(titanic, c(Survived, Sex))
```

```{r, create a new dataset from the selected data}
#Let's name the dataset with just the two columns, Survived and Sex
#TASK: Write the function to save the two columns as one new dataset
#and give it a name
titanic_survived_and_sex <- select(titanic, c(Survived, Sex))
```

```{r, creating a subset of selected}
#Let's get rid of the Sex column in the new dataset created above
#TASK: Write the function that deselects the sex column
#(hint: use the 'select' function to not select a -column)
titanic_survived_and_sex %>% select(Survived)
```

```{r, renaming a column}
#Let's rename a column name
#TASK: Write the function that renames 'Sex' to 'Gender'
colnames(titanic)[2] ="Gender"
```

```{r, making a new dataframe with the new column name}
#Let's make a new dataframe with the new column name
#TASK: Write the function that names a new dataset that includes the 'gender' column
titanic_gender <- select(titanic, Gender)
```

```{r, filtering just the males }
#Let's 'filter' just the males from our dataset
#TASK: Write the function that includes only rows that are 'male'
titanic_gender_male <- subset(titanic, Gender = "Male")
```

```{r, arranging data}
#Let's 'arrange' our data by gender (not the data you just filtered)
#TASK: Write the function to group the data by gender (hint: arrange())
arrange(titanic, Gender)
```
